// #define DEBUGWAVEANALYSIS
// #define DEBUGDRAWOPTION
// #define GETDATA

// #define OPENFITWAVE

#define MAXLENGTH 32768
#define POLARITY 1

// Baseline
#define PRETRIGGER    100
#define BASELINESTDCHECK 10.

// RCCR2 Parameters
#define RCCR2PARPRETRIGGER    60
#define RCCR2PARSMOOTHLENGTH  20
#define RCCR2PARRISELENGTH    40
#define RCCR2PARTHRESHOLD     5

// Trapezoid Parameters
#define TRAPPARDECAYLENGTH  20000
#define TRAPPARRISELENGTH   380
#define TRAPPARFLATTOP      320
#define TRAPPARPRITRIGGER   100
#define TRAPPARPEAKDELAY    0
#define TRAPPARPEAKMEAN     0

//
#define PILEUPMAX 3

// Fit Parameters
#define FITTAUP 40000
#define FITTAUR 100